CREATE_FILE_MONITORING_TABLE = """
CREATE TABLE IF NOT EXISTS file_monitoring (
    id INT AUTO_INCREMENT PRIMARY KEY,
    source VARCHAR(255) NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    timestamp DATETIME NOT NULL
);"""

CREATE_STAGE_EXECUTION_TABLE = """
CREATE TABLE IF NOT EXISTS stage_execution (
    id INT AUTO_INCREMENT PRIMARY KEY,
    stage_name VARCHAR(255) NOT NULL,
    start_time DATETIME NOT NULL,
    end_time DATETIME NOT NULL
);"""
